### ISSUE TITLE
blip2zh-chatglm-6b model missing 2 required positional arguments query and history

### ISSUE THREAD

**Issue by vergil-ong** [XiPotatonium/chatbot-webui#1]
I clone the code into local，and copy Xipotzzz/blip2zh-chatglm-6b model from https://huggingface.co/Xipotzzz/blip2zh-chatglm-6b
and then run python launch.py cfgs/blip2zh-chatglm-6b.json 

now I could view the web service, 
but if I input somthing text or image to send , the web will reponse nothing, and console will report the error

missing 2 required positional arguments 'query' and 'history'

![Uploading image.png…]()

GPU : GTX 4070 12G
OS : windows 10
CUDA:12.1
pytorch: 1.13.1

GPU device is OK

**Comment by XiPotatonium** [comment]
There is a version mismatch. I have uploaded a new version of blip2chatglm at [huggingface](https://huggingface.co/Xipotzzz/blip2zh-chatglm-6b/tree/main). Please use the new version of modeling_blip2chatglm.py.

**Comment by vergil-ong** [comment]
it works， thank you
